local M = {}

local c = require("vscode_clean.palette")

local function set_groups(groups)
  for group, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, group, spec)
  end
end

local function set_links(links)
  for group, target in pairs(links) do
    vim.api.nvim_set_hl(0, group, { link = target })
  end
end

local groups = {
  -- Editor UI
  Normal = { fg = c.fg, bg = c.bg },
  NormalNC = { fg = c.fg, bg = c.bg },
  NormalFloat = { fg = c.fg, bg = c.surface },
  FloatBorder = { fg = c.border, bg = c.surface },
  FloatTitle = { fg = c.blue, bg = c.surface, bold = true },
  FloatFooter = { fg = c.muted, bg = c.surface },
  Cursor = { fg = c.bg, bg = c.cursor },
  lCursor = { fg = c.bg, bg = c.cursor },
  CursorIM = { fg = c.bg, bg = c.cursor },
  CursorColumn = { bg = c.line },
  CursorLine = { bg = c.line },
  ColorColumn = { bg = c.surface },
  LineNr = { fg = c.dim, bg = c.bg },
  LineNrAbove = { fg = c.dim, bg = c.bg },
  LineNrBelow = { fg = c.dim, bg = c.bg },
  CursorLineNr = { fg = c.bright_blue, bg = c.line, bold = true },
  CursorLineSign = { bg = c.line },
  CursorLineFold = { bg = c.line },
  SignColumn = { fg = c.dim, bg = c.bg },
  FoldColumn = { fg = c.dim, bg = c.bg },
  Folded = { fg = c.muted, bg = c.line },
  WinSeparator = { fg = c.border, bg = c.bg },
  EndOfBuffer = { fg = c.bg, bg = c.bg },
  NonText = { fg = c.dim },
  Whitespace = { fg = c.whitespace },
  SpecialKey = { fg = c.dim },
  Conceal = { fg = c.dim },
  Directory = { fg = c.cyan },
  Title = { fg = c.blue, bold = true },
  Visual = { bg = c.visual },
  VisualNOS = { bg = c.visual },
  Search = { fg = c.bright, bg = c.search },
  CurSearch = { fg = c.bg, bg = c.yellow, bold = true },
  IncSearch = { fg = c.bg, bg = c.yellow, bold = true },
  Substitute = { fg = c.bright, bg = c.soft_red },
  MatchParen = { fg = c.bright_blue, bg = c.elevated, bold = true, underline = true },
  QuickFixLine = { bg = c.visual, bold = true },

  -- Menus and command UI
  Pmenu = { fg = c.fg, bg = c.surface },
  PmenuSel = { fg = c.bright, bg = c.visual },
  PmenuSbar = { bg = c.elevated },
  PmenuThumb = { bg = c.dim },
  PmenuMatch = { fg = c.yellow, bg = c.surface, bold = true },
  PmenuMatchSel = { fg = c.yellow, bg = c.visual, bold = true },
  PmenuKind = { fg = c.cyan, bg = c.surface },
  PmenuKindSel = { fg = c.cyan, bg = c.visual },
  PmenuExtra = { fg = c.muted, bg = c.surface },
  PmenuExtraSel = { fg = c.fg, bg = c.visual },
  PmenuBorder = { fg = c.border, bg = c.surface },
  PmenuShadow = { bg = c.sidebar, blend = 20 },
  PmenuShadowThrough = { bg = c.sidebar, blend = 40 },
  WildMenu = { fg = c.bright, bg = c.focus, bold = true },
  ComplMatchIns = { fg = c.yellow, bold = true },

  -- Bars and messages
  StatusLine = { fg = c.fg, bg = c.sidebar },
  StatusLineNC = { fg = c.dim, bg = c.sidebar },
  WinBar = { fg = c.fg, bg = c.bg },
  WinBarNC = { fg = c.dim, bg = c.bg },
  TabLine = { fg = c.muted, bg = c.sidebar },
  TabLineFill = { fg = c.muted, bg = c.sidebar },
  TabLineSel = { fg = c.bright, bg = c.elevated, bold = true },
  MsgArea = { fg = c.fg, bg = c.bg },
  MsgSeparator = { fg = c.border, bg = c.sidebar },
  ModeMsg = { fg = c.blue, bold = true },
  MoreMsg = { fg = c.green },
  Question = { fg = c.cyan },
  ErrorMsg = { fg = c.red, bold = true },
  WarningMsg = { fg = c.gold, bold = true },

  -- Diffs and spelling
  DiffAdd = { fg = c.green, bg = c.diff_add },
  DiffChange = { fg = c.bright_blue, bg = c.diff_change },
  DiffDelete = { fg = c.red, bg = c.diff_delete },
  DiffText = { fg = c.bright, bg = c.focus, bold = true },
  Added = { fg = c.green },
  Changed = { fg = c.bright_blue },
  Removed = { fg = c.red },
  SpellBad = { undercurl = true, sp = c.red },
  SpellCap = { undercurl = true, sp = c.blue },
  SpellLocal = { undercurl = true, sp = c.cyan },
  SpellRare = { undercurl = true, sp = c.gold },

  -- Traditional syntax
  Comment = { fg = c.comment },
  Constant = { fg = c.pale_green },
  String = { fg = c.orange },
  Character = { fg = c.orange },
  Number = { fg = c.pale_green },
  Boolean = { fg = c.blue },
  Float = { fg = c.pale_green },
  Identifier = { fg = c.fg },
  Function = { fg = c.yellow },
  Statement = { fg = c.blue },
  Conditional = { fg = c.blue },
  Repeat = { fg = c.blue },
  Label = { fg = c.blue },
  Operator = { fg = c.fg },
  Keyword = { fg = c.blue },
  Exception = { fg = c.blue },
  PreProc = { fg = c.blue },
  Include = { fg = c.blue },
  Define = { fg = c.blue },
  Macro = { fg = c.cyan },
  PreCondit = { fg = c.blue },
  Type = { fg = c.cyan },
  StorageClass = { fg = c.blue },
  Structure = { fg = c.cyan },
  Typedef = { fg = c.cyan },
  Special = { fg = c.gold },
  SpecialChar = { fg = c.gold },
  Tag = { fg = c.blue },
  Delimiter = { fg = c.fg },
  SpecialComment = { fg = c.comment, bold = true },
  Debug = { fg = c.gold },
  Bold = { bold = true },
  Italic = { italic = true },
  Strikethrough = { strikethrough = true },
  Underlined = { fg = c.bright_blue, underline = true },
  Ignore = { fg = c.dim },
  Error = { fg = c.red },
  Todo = { fg = c.bg, bg = c.yellow, bold = true },

  -- Tree-sitter details
  ["@variable"] = { fg = c.fg },
  ["@variable.builtin"] = { fg = c.cyan },
  ["@variable.parameter"] = { fg = c.bright_blue },
  ["@variable.parameter.builtin"] = { fg = c.cyan },
  ["@variable.member"] = { fg = c.bright_blue },
  ["@property"] = { fg = c.bright_blue },
  ["@attribute"] = { fg = c.cyan },
  ["@module"] = { fg = c.cyan },
  ["@module.builtin"] = { fg = c.cyan },
  ["@constructor"] = { fg = c.cyan },
  ["@string.escape"] = { fg = c.gold },
  ["@string.special"] = { fg = c.gold },
  ["@string.special.url"] = { fg = c.bright_blue, underline = true },
  ["@character.special"] = { fg = c.gold },
  ["@punctuation.delimiter"] = { fg = c.fg },
  ["@punctuation.bracket"] = { fg = c.fg },
  ["@punctuation.special"] = { fg = c.gold },
  ["@keyword.directive"] = { fg = c.blue },
  ["@keyword.directive.define"] = { fg = c.blue },
  ["@markup.heading.1"] = { fg = c.blue, bold = true },
  ["@markup.heading.2"] = { fg = c.cyan, bold = true },
  ["@markup.heading.3"] = { fg = c.green, bold = true },
  ["@markup.heading.4"] = { fg = c.yellow, bold = true },
  ["@markup.heading.5"] = { fg = c.orange, bold = true },
  ["@markup.heading.6"] = { fg = c.red, bold = true },
  ["@markup.link"] = { fg = c.bright_blue },
  ["@markup.link.label"] = { fg = c.cyan },
  ["@markup.link.url"] = { fg = c.bright_blue, underline = true },
  ["@markup.raw"] = { fg = c.orange },
  ["@markup.raw.block"] = { fg = c.orange },
  ["@markup.list"] = { fg = c.blue },
  ["@markup.quote"] = { fg = c.comment },

  -- Diagnostics and LSP
  DiagnosticError = { fg = c.red },
  DiagnosticWarn = { fg = c.gold },
  DiagnosticInfo = { fg = c.bright_blue },
  DiagnosticHint = { fg = c.cyan },
  DiagnosticOk = { fg = c.green },
  DiagnosticVirtualTextError = { fg = c.red, bg = c.diff_delete },
  DiagnosticVirtualTextWarn = { fg = c.gold, bg = c.surface },
  DiagnosticVirtualTextInfo = { fg = c.bright_blue, bg = c.diff_change },
  DiagnosticVirtualTextHint = { fg = c.cyan, bg = c.surface },
  DiagnosticVirtualTextOk = { fg = c.green, bg = c.diff_add },
  DiagnosticUnderlineError = { undercurl = true, sp = c.red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = c.gold },
  DiagnosticUnderlineInfo = { undercurl = true, sp = c.bright_blue },
  DiagnosticUnderlineHint = { undercurl = true, sp = c.cyan },
  DiagnosticUnderlineOk = { undercurl = true, sp = c.green },
  DiagnosticDeprecated = { strikethrough = true, sp = c.dim },
  DiagnosticUnnecessary = { fg = c.dim },
  LspReferenceText = { bg = c.elevated },
  LspReferenceRead = { bg = c.elevated },
  LspReferenceWrite = { bg = c.visual, underline = true },
  LspInlayHint = { fg = c.dim, bg = c.surface, italic = true },
  LspCodeLens = { fg = c.dim },
  LspCodeLensSeparator = { fg = c.border },
  LspSignatureActiveParameter = { fg = c.yellow, bold = true },

  -- Git
  GitSignsAdd = { fg = c.green },
  GitSignsChange = { fg = c.bright_blue },
  GitSignsDelete = { fg = c.red },
  GitSignsChangedelete = { fg = c.orange },
  GitSignsTopdelete = { fg = c.red },
  GitSignsUntracked = { fg = c.green },
  GitSignsAddPreview = { fg = c.green, bg = c.diff_add },
  GitSignsDeletePreview = { fg = c.red, bg = c.diff_delete },
  GitSignsCurrentLineBlame = { fg = c.dim, italic = true },

  -- Snacks UI
  SnacksNormal = { fg = c.fg, bg = c.surface },
  SnacksNormalNC = { fg = c.fg, bg = c.surface },
  SnacksWinBar = { fg = c.fg, bg = c.surface },
  SnacksWinBarNC = { fg = c.dim, bg = c.surface },
  SnacksWinSeparator = { fg = c.border, bg = c.bg },
  SnacksTitle = { fg = c.blue, bg = c.surface, bold = true },
  SnacksFooter = { fg = c.muted, bg = c.surface },
  SnacksInputNormal = { fg = c.fg, bg = c.surface },
  SnacksInputBorder = { fg = c.focus, bg = c.surface },
  SnacksInputTitle = { fg = c.blue, bg = c.surface, bold = true },
  SnacksInputIcon = { fg = c.cyan, bg = c.surface },
  SnacksPickerMatch = { fg = c.yellow, bold = true },
  SnacksPickerSearch = { fg = c.yellow, bold = true },
  SnacksPickerInputSearch = { fg = c.yellow },
  SnacksPickerDir = { fg = c.cyan },
  SnacksPickerDirectory = { fg = c.cyan },
  SnacksPickerFile = { fg = c.fg },
  SnacksPickerListCursorLine = { bg = c.visual },
  SnacksPickerPreviewCursorLine = { bg = c.line },
  SnacksPickerSelected = { fg = c.bright_blue },
  SnacksPickerDimmed = { fg = c.dim },
  SnacksPickerPathHidden = { fg = c.dim },
  SnacksPickerPathIgnored = { fg = c.dim },
  SnacksPickerGitStatusAdded = { fg = c.green },
  SnacksPickerGitStatusCopied = { fg = c.green },
  SnacksPickerGitStatusDeleted = { fg = c.red },
  SnacksPickerGitStatusModified = { fg = c.bright_blue },
  SnacksPickerGitStatusRenamed = { fg = c.cyan },
  SnacksPickerGitStatusStaged = { fg = c.green },
  SnacksPickerGitStatusUnmerged = { fg = c.gold },
  SnacksPickerGitStatusUntracked = { fg = c.green },
  SnacksIndent = { fg = c.whitespace },
  SnacksIndentScope = { fg = c.focus },
  SnacksIndentChunk = { fg = c.focus },
  SnacksGhPurple = { fg = c.blue },

  -- Completion
  BlinkCmpMenu = { fg = c.fg, bg = c.surface },
  BlinkCmpMenuBorder = { fg = c.border, bg = c.surface },
  BlinkCmpMenuSelection = { fg = c.bright, bg = c.visual },
  BlinkCmpLabel = { fg = c.fg },
  BlinkCmpLabelDeprecated = { fg = c.dim, strikethrough = true },
  BlinkCmpLabelMatch = { fg = c.yellow, bold = true },
  BlinkCmpLabelDetail = { fg = c.muted },
  BlinkCmpLabelDescription = { fg = c.dim },
  BlinkCmpKind = { fg = c.cyan },
  BlinkCmpSource = { fg = c.dim },
  BlinkCmpGhostText = { fg = c.dim, italic = true },
  BlinkCmpDoc = { fg = c.fg, bg = c.surface },
  BlinkCmpDocBorder = { fg = c.border, bg = c.surface },
  BlinkCmpDocSeparator = { fg = c.border, bg = c.surface },
  BlinkCmpDocCursorLine = { bg = c.line },
  BlinkCmpSignatureHelp = { fg = c.fg, bg = c.surface },
  BlinkCmpSignatureHelpBorder = { fg = c.border, bg = c.surface },
  BlinkCmpSignatureHelpActiveParameter = { fg = c.yellow, bold = true },
  BlinkCmpScrollBarGutter = { bg = c.elevated },
  BlinkCmpScrollBarThumb = { bg = c.dim },

  -- Bufferline
  BufferLineFill = { bg = c.sidebar },
  BufferLineBackground = { fg = c.dim, bg = c.sidebar },
  BufferLineBufferVisible = { fg = c.muted, bg = c.sidebar },
  BufferLineBufferSelected = { fg = c.bright, bg = c.elevated, bold = true },
  BufferLineIndicatorSelected = { fg = c.focus, bg = c.elevated },
  BufferLineSeparator = { fg = c.sidebar, bg = c.sidebar },
  BufferLineSeparatorVisible = { fg = c.sidebar, bg = c.sidebar },
  BufferLineSeparatorSelected = { fg = c.elevated, bg = c.elevated },
  BufferLineModified = { fg = c.gold, bg = c.sidebar },
  BufferLineModifiedVisible = { fg = c.gold, bg = c.sidebar },
  BufferLineModifiedSelected = { fg = c.gold, bg = c.elevated },
  BufferLinePick = { fg = c.red, bg = c.sidebar, bold = true },
  BufferLinePickVisible = { fg = c.red, bg = c.sidebar, bold = true },
  BufferLinePickSelected = { fg = c.red, bg = c.elevated, bold = true },
  BufferLineOffsetSeparator = { fg = c.border, bg = c.sidebar },
  BufferLineTruncMarker = { fg = c.dim, bg = c.sidebar },

  -- Which-key and icons
  WhichKeyNormal = { fg = c.fg, bg = c.surface },
  WhichKeyBorder = { fg = c.border, bg = c.surface },
  WhichKeyTitle = { fg = c.blue, bg = c.surface, bold = true },
  WhichKeyGroup = { fg = c.cyan },
  WhichKeyDesc = { fg = c.fg },
  WhichKeySeparator = { fg = c.dim },
  WhichKeyValue = { fg = c.muted },
  WhichKeyIconPurple = { fg = c.blue },
  WhichKeyColorPurple = { fg = c.blue },
  MiniIconsDefault = { fg = c.fg },
  MiniIconsAzure = { fg = c.bright_blue },
  MiniIconsBlue = { fg = c.blue },
  MiniIconsCyan = { fg = c.cyan },
  MiniIconsGreen = { fg = c.green },
  MiniIconsGrey = { fg = c.muted },
  MiniIconsOrange = { fg = c.orange },
  MiniIconsPurple = { fg = c.blue },
  MiniIconsRed = { fg = c.red },
  MiniIconsYellow = { fg = c.yellow },

  -- Flash
  FlashBackdrop = { fg = c.dim },
  FlashMatch = { fg = c.fg, bg = c.visual },
  FlashCurrent = { fg = c.bright, bg = c.soft_red, bold = true },
  FlashLabel = { fg = c.bright, bg = c.soft_red, bold = true },
  FlashPrompt = { fg = c.fg, bg = c.surface },
  FlashPromptIcon = { fg = c.red, bg = c.surface },

  -- Noice
  NoiceCmdlinePopup = { fg = c.fg, bg = c.surface },
  NoiceCmdlinePopupBorder = { fg = c.focus, bg = c.surface },
  NoiceCmdlinePopupTitle = { fg = c.blue, bg = c.surface, bold = true },
  NoiceConfirm = { fg = c.fg, bg = c.surface },
  NoiceConfirmBorder = { fg = c.focus, bg = c.surface },
  NoicePopup = { fg = c.fg, bg = c.surface },
  NoicePopupBorder = { fg = c.border, bg = c.surface },
  NoicePopupmenu = { fg = c.fg, bg = c.surface },
  NoicePopupmenuBorder = { fg = c.border, bg = c.surface },
  NoicePopupmenuSelected = { fg = c.bright, bg = c.visual },
  NoicePopupmenuMatch = { fg = c.yellow, bold = true },
  NoiceMini = { fg = c.fg, bg = c.elevated },
  NoiceFormatProgressDone = { fg = c.bg, bg = c.green },
  NoiceFormatProgressTodo = { fg = c.dim, bg = c.elevated },

  -- Trouble
  TroubleNormal = { fg = c.fg, bg = c.sidebar },
  TroubleNormalNC = { fg = c.fg, bg = c.sidebar },
  TroubleText = { fg = c.fg },
  TroubleCount = { fg = c.bg, bg = c.blue, bold = true },
  TroubleCode = { fg = c.muted },
  TroubleSource = { fg = c.dim },
  TroublePos = { fg = c.dim },
  TroubleDirectory = { fg = c.cyan },
  TroubleFilename = { fg = c.fg },
  TroublePreview = { bg = c.visual },

  -- Telescope compatibility
  TelescopeNormal = { fg = c.fg, bg = c.surface },
  TelescopeBorder = { fg = c.border, bg = c.surface },
  TelescopeTitle = { fg = c.blue, bg = c.surface, bold = true },
  TelescopePromptNormal = { fg = c.fg, bg = c.elevated },
  TelescopePromptBorder = { fg = c.focus, bg = c.elevated },
  TelescopePromptTitle = { fg = c.blue, bg = c.elevated, bold = true },
  TelescopePromptPrefix = { fg = c.cyan, bg = c.elevated },
  TelescopeResultsNormal = { fg = c.fg, bg = c.surface },
  TelescopeResultsBorder = { fg = c.border, bg = c.surface },
  TelescopePreviewNormal = { fg = c.fg, bg = c.surface },
  TelescopePreviewBorder = { fg = c.border, bg = c.surface },
  TelescopeSelection = { fg = c.bright, bg = c.visual },
  TelescopeSelectionCaret = { fg = c.focus, bg = c.visual },
  TelescopeMatching = { fg = c.yellow, bold = true },

  -- Neo-tree compatibility
  NeoTreeNormal = { fg = c.fg, bg = c.sidebar },
  NeoTreeNormalNC = { fg = c.fg, bg = c.sidebar },
  NeoTreeEndOfBuffer = { fg = c.sidebar, bg = c.sidebar },
  NeoTreeWinSeparator = { fg = c.border, bg = c.sidebar },
  NeoTreeDirectoryIcon = { fg = c.cyan },
  NeoTreeDirectoryName = { fg = c.cyan },
  NeoTreeRootName = { fg = c.blue, bold = true },
  NeoTreeFileName = { fg = c.fg },
  NeoTreeFileNameOpened = { fg = c.bright, bold = true },
  NeoTreeIndentMarker = { fg = c.whitespace },
  NeoTreeExpander = { fg = c.dim },
  NeoTreeGitAdded = { fg = c.green },
  NeoTreeGitModified = { fg = c.bright_blue },
  NeoTreeGitDeleted = { fg = c.red },
  NeoTreeGitConflict = { fg = c.gold },
  NeoTreeGitUntracked = { fg = c.green },
  NeoTreeGitIgnored = { fg = c.dim },

  -- Indentation, context, and delimiter compatibility
  IblIndent = { fg = c.whitespace },
  IblWhitespace = { fg = c.whitespace },
  IblScope = { fg = c.focus },
  TreesitterContext = { bg = c.surface },
  TreesitterContextLineNumber = { fg = c.bright_blue, bg = c.surface },
  RainbowDelimiterRed = { fg = c.red },
  RainbowDelimiterYellow = { fg = c.yellow },
  RainbowDelimiterBlue = { fg = c.blue },
  RainbowDelimiterOrange = { fg = c.orange },
  RainbowDelimiterGreen = { fg = c.green },
  RainbowDelimiterViolet = { fg = c.bright_blue },
  RainbowDelimiterCyan = { fg = c.cyan },
}

local links = {
  VertSplit = "WinSeparator",
  NormalSB = "Normal",

  ["@comment"] = "Comment",
  ["@comment.documentation"] = "Comment",
  ["@comment.error"] = "DiagnosticError",
  ["@comment.warning"] = "DiagnosticWarn",
  ["@comment.todo"] = "Todo",
  ["@comment.note"] = "DiagnosticInfo",
  ["@constant"] = "Constant",
  ["@constant.builtin"] = "Constant",
  ["@constant.macro"] = "Macro",
  ["@string"] = "String",
  ["@string.documentation"] = "String",
  ["@string.regexp"] = "String",
  ["@string.regex"] = "String",
  ["@character"] = "Character",
  ["@character.special"] = "SpecialChar",
  ["@boolean"] = "Boolean",
  ["@number"] = "Number",
  ["@number.float"] = "Float",
  ["@float"] = "Float",
  ["@function"] = "Function",
  ["@function.builtin"] = "Function",
  ["@function.call"] = "Function",
  ["@function.macro"] = "Macro",
  ["@function.method"] = "Function",
  ["@function.method.call"] = "Function",
  ["@method"] = "Function",
  ["@method.call"] = "Function",
  ["@keyword"] = "Keyword",
  ["@keyword.coroutine"] = "Keyword",
  ["@keyword.function"] = "Keyword",
  ["@keyword.operator"] = "Keyword",
  ["@keyword.import"] = "Include",
  ["@keyword.type"] = "Keyword",
  ["@keyword.modifier"] = "Keyword",
  ["@keyword.repeat"] = "Repeat",
  ["@keyword.return"] = "Keyword",
  ["@keyword.debug"] = "Debug",
  ["@keyword.exception"] = "Exception",
  ["@keyword.conditional"] = "Conditional",
  ["@keyword.conditional.ternary"] = "Conditional",
  ["@conditional"] = "Conditional",
  ["@repeat"] = "Repeat",
  ["@label"] = "Label",
  ["@operator"] = "Operator",
  ["@type"] = "Type",
  ["@type.builtin"] = "Type",
  ["@type.definition"] = "Typedef",
  ["@type.qualifier"] = "Keyword",
  ["@class"] = "Type",
  ["@tag"] = "Tag",
  ["@tag.attribute"] = "@property",
  ["@tag.delimiter"] = "Delimiter",
  ["@markup.strong"] = "Bold",
  ["@markup.italic"] = "Italic",
  ["@markup.strikethrough"] = "Strikethrough",
  ["@markup.underline"] = "Underlined",
  ["@diff.plus"] = "Added",
  ["@diff.minus"] = "Removed",
  ["@diff.delta"] = "Changed",

  ["@lsp.type.class"] = "Type",
  ["@lsp.type.comment"] = "Comment",
  ["@lsp.type.decorator"] = "@attribute",
  ["@lsp.type.enum"] = "Type",
  ["@lsp.type.enumMember"] = "Constant",
  ["@lsp.type.event"] = "Function",
  ["@lsp.type.function"] = "Function",
  ["@lsp.type.interface"] = "Type",
  ["@lsp.type.keyword"] = "Keyword",
  ["@lsp.type.macro"] = "Macro",
  ["@lsp.type.method"] = "Function",
  ["@lsp.type.modifier"] = "Keyword",
  ["@lsp.type.namespace"] = "@module",
  ["@lsp.type.number"] = "Number",
  ["@lsp.type.operator"] = "Operator",
  ["@lsp.type.parameter"] = "@variable.parameter",
  ["@lsp.type.property"] = "@property",
  ["@lsp.type.regexp"] = "String",
  ["@lsp.type.string"] = "String",
  ["@lsp.type.struct"] = "Type",
  ["@lsp.type.type"] = "Type",
  ["@lsp.type.typeParameter"] = "Type",
  ["@lsp.type.variable"] = "@variable",
  ["@lsp.mod.deprecated"] = "DiagnosticDeprecated",
  ["@lsp.typemod.variable.readonly"] = "Constant",
  ["@lsp.typemod.property.readonly"] = "Constant",
  ["@lsp.typemod.variable.defaultLibrary"] = "@variable.builtin",
  ["@lsp.typemod.function.defaultLibrary"] = "@function.builtin",
  ["@lsp.typemod.method.defaultLibrary"] = "@function.builtin",

  DiagnosticSignError = "DiagnosticError",
  DiagnosticSignWarn = "DiagnosticWarn",
  DiagnosticSignInfo = "DiagnosticInfo",
  DiagnosticSignHint = "DiagnosticHint",
  DiagnosticSignOk = "DiagnosticOk",
  DiagnosticFloatingError = "DiagnosticError",
  DiagnosticFloatingWarn = "DiagnosticWarn",
  DiagnosticFloatingInfo = "DiagnosticInfo",
  DiagnosticFloatingHint = "DiagnosticHint",
  DiagnosticFloatingOk = "DiagnosticOk",
  DiagnosticVirtualLinesError = "DiagnosticVirtualTextError",
  DiagnosticVirtualLinesWarn = "DiagnosticVirtualTextWarn",
  DiagnosticVirtualLinesInfo = "DiagnosticVirtualTextInfo",
  DiagnosticVirtualLinesHint = "DiagnosticVirtualTextHint",
  DiagnosticVirtualLinesOk = "DiagnosticVirtualTextOk",

  GitSignsStagedAdd = "GitSignsAdd",
  GitSignsStagedChange = "GitSignsChange",
  GitSignsStagedDelete = "GitSignsDelete",
  GitSignsStagedChangedelete = "GitSignsChangedelete",
  GitSignsStagedTopdelete = "GitSignsTopdelete",

  SnacksPicker = "SnacksNormal",
  SnacksPickerList = "SnacksNormal",
  SnacksPickerInput = "SnacksNormal",
  SnacksPickerPreview = "SnacksNormal",
  SnacksPickerBox = "SnacksNormal",
  SnacksPickerIcon = "Special",
  SnacksPickerIdx = "Number",
  SnacksPickerRow = "LineNr",
  SnacksPickerCol = "LineNr",
  SnacksPickerSpecial = "Special",
  SnacksPickerComment = "Comment",
  SnacksPickerTotals = "Comment",
  SnacksPickerPrompt = "Special",
  SnacksPickerGitBranch = "Directory",
  SnacksPickerGitBranchCurrent = "GitSignsAdd",
  SnacksPickerGitDate = "Comment",
  SnacksPickerGitAuthor = "String",
  SnacksPickerGitCommit = "Number",
  SnacksPickerLink = "Underlined",
  SnacksPickerLinkBroken = "DiagnosticError",
  SnacksPickerUnselected = "Comment",
  SnacksPickerBold = "Bold",
  SnacksPickerItalic = "Italic",
  SnacksPickerToggle = "Special",
  SnacksDashboardNormal = "Normal",
  SnacksDashboardHeader = "Title",
  SnacksDashboardFooter = "Comment",
  SnacksDashboardDesc = "Normal",
  SnacksDashboardIcon = "Special",
  SnacksDashboardKey = "Keyword",
  SnacksDashboardSpecial = "Special",
  SnacksDashboardDir = "Directory",
  SnacksNotifierInfo = "DiagnosticInfo",
  SnacksNotifierWarn = "DiagnosticWarn",
  SnacksNotifierError = "DiagnosticError",
  SnacksNotifierDebug = "Debug",
  SnacksNotifierTrace = "Comment",
  SnacksNotifierBorderInfo = "DiagnosticInfo",
  SnacksNotifierBorderWarn = "DiagnosticWarn",
  SnacksNotifierBorderError = "DiagnosticError",
  SnacksNotifierBorderDebug = "Debug",
  SnacksNotifierBorderTrace = "Comment",

  BlinkCmpKindText = "Normal",
  BlinkCmpKindMethod = "Function",
  BlinkCmpKindFunction = "Function",
  BlinkCmpKindConstructor = "Type",
  BlinkCmpKindField = "@property",
  BlinkCmpKindVariable = "@variable",
  BlinkCmpKindClass = "Type",
  BlinkCmpKindInterface = "Type",
  BlinkCmpKindModule = "@module",
  BlinkCmpKindProperty = "@property",
  BlinkCmpKindUnit = "Number",
  BlinkCmpKindValue = "Constant",
  BlinkCmpKindEnum = "Type",
  BlinkCmpKindKeyword = "Keyword",
  BlinkCmpKindSnippet = "Special",
  BlinkCmpKindColor = "Special",
  BlinkCmpKindFile = "Directory",
  BlinkCmpKindReference = "Underlined",
  BlinkCmpKindFolder = "Directory",
  BlinkCmpKindEnumMember = "Constant",
  BlinkCmpKindConstant = "Constant",
  BlinkCmpKindStruct = "Type",
  BlinkCmpKindEvent = "Function",
  BlinkCmpKindOperator = "Operator",
  BlinkCmpKindTypeParameter = "Type",

  BufferLineCloseButton = "BufferLineBackground",
  BufferLineCloseButtonVisible = "BufferLineBufferVisible",
  BufferLineCloseButtonSelected = "BufferLineBufferSelected",
  BufferLineNumbers = "BufferLineBackground",
  BufferLineNumbersVisible = "BufferLineBufferVisible",
  BufferLineNumbersSelected = "BufferLineBufferSelected",
  BufferLineDuplicate = "BufferLineBackground",
  BufferLineDuplicateVisible = "BufferLineBufferVisible",
  BufferLineDuplicateSelected = "BufferLineBufferSelected",
  BufferLineDiagnostic = "BufferLineBackground",
  BufferLineDiagnosticVisible = "BufferLineBufferVisible",
  BufferLineDiagnosticSelected = "BufferLineBufferSelected",
  BufferLineError = "DiagnosticError",
  BufferLineErrorVisible = "DiagnosticError",
  BufferLineErrorSelected = "DiagnosticError",
  BufferLineWarning = "DiagnosticWarn",
  BufferLineWarningVisible = "DiagnosticWarn",
  BufferLineWarningSelected = "DiagnosticWarn",
  BufferLineInfo = "DiagnosticInfo",
  BufferLineInfoVisible = "DiagnosticInfo",
  BufferLineInfoSelected = "DiagnosticInfo",
  BufferLineHint = "DiagnosticHint",
  BufferLineHintVisible = "DiagnosticHint",
  BufferLineHintSelected = "DiagnosticHint",

  CmpItemAbbr = "BlinkCmpLabel",
  CmpItemAbbrDeprecated = "BlinkCmpLabelDeprecated",
  CmpItemAbbrMatch = "BlinkCmpLabelMatch",
  CmpItemAbbrMatchFuzzy = "BlinkCmpLabelMatch",
  CmpItemMenu = "BlinkCmpSource",

  WhichKeyIconAzure = "MiniIconsAzure",
  WhichKeyIconBlue = "MiniIconsBlue",
  WhichKeyIconCyan = "MiniIconsCyan",
  WhichKeyIconGreen = "MiniIconsGreen",
  WhichKeyIconGrey = "MiniIconsGrey",
  WhichKeyIconOrange = "MiniIconsOrange",
  WhichKeyIconPurple = "MiniIconsBlue",
  WhichKeyIconRed = "MiniIconsRed",
  WhichKeyIconYellow = "MiniIconsYellow",
  WhichKeyColorAzure = "MiniIconsAzure",
  WhichKeyColorBlue = "MiniIconsBlue",
  WhichKeyColorCyan = "MiniIconsCyan",
  WhichKeyColorGreen = "MiniIconsGreen",
  WhichKeyColorGrey = "MiniIconsGrey",
  WhichKeyColorOrange = "MiniIconsOrange",
  WhichKeyColorPurple = "MiniIconsBlue",
  WhichKeyColorRed = "MiniIconsRed",
  WhichKeyColorYellow = "MiniIconsYellow",

  NoiceCmdlineIcon = "Special",
  NoiceFormatTitle = "Title",
  NoiceFormatLevelError = "DiagnosticError",
  NoiceFormatLevelWarn = "DiagnosticWarn",
  NoiceFormatLevelInfo = "DiagnosticInfo",
  NoiceFormatLevelDebug = "Debug",
  NoiceFormatLevelTrace = "Comment",

  TroubleIconDirectory = "Directory",
  TroubleIndent = "NonText",
  TroubleIcon = "Special",
}

local terminal_colors = {
  c.bg,
  c.red,
  c.green,
  c.yellow,
  c.blue,
  c.orange,
  c.cyan,
  c.fg,
  c.dim,
  c.soft_red,
  c.green,
  c.gold,
  c.bright_blue,
  c.orange,
  c.cyan,
  c.bright,
}

function M.apply()
  set_groups(groups)
  set_links(links)

  for index, color in ipairs(terminal_colors) do
    vim.g["terminal_color_" .. (index - 1)] = color
  end
end

function M.load()
  vim.o.background = "dark"
  vim.o.termguicolors = true

  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end

  vim.g.colors_name = "vscode-clean"
  M.apply()
end

return M
