enable_audio_bell no

map f23 discard_event
map f24 discard_event

map ctrl+tab
map ctrl+shift+tab
map ctrl+tab send_text normal,application \x1b[9;5u
map ctrl+shift+tab send_text normal,application \x1b[9;6u
