# 1. Change prefix from Ctrl-b to Ctrl-s (More ergonomic)
set -g prefix C-s
unbind C-b
bind C-s send-prefix

# 2. Bind 'r' to reload configuration easily
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# 3. Enable mouse support (Resizing panes, selecting windows)
set -g mouse on

# 4. Use Vim keys (h, j, k, l) for pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# 5. Move status bar to the top
set-option -g status-position top

# =====================================
# Tmux Plugin Manager (TPM) & Plugins
# =====================================

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

# Catppuccin theme customization (v2.x style)
set -g @catppuccin_flavor 'mocha' # mocha, macchiato, frappe, latte
set -g @catppuccin_window_status_style "rounded"

# Status line configuration
set -g status-left ""
set -g status-right-length 100
set -g status-left-length 100

set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_date_time}"

# Separators
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

# Initialize TMUX plugin manager (Keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
